name: Sync Fork

on:
  schedule:
    - cron: '0 5/6 * * *'
  workflow_dispatch:

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          github_token: ${{ secrets.REPO_PAT }}
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          owner: containrrr
          base: main
          head: main
          pr_title: Merge
          auto_approve: true
