name: Sync Fork

on:
  schedule:
    - cron: '0 7/6 * * *'
  workflow_dispatch:

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          token: ${{ secrets.BOT_TOKEN }}
          owner: containrrr
          base: main
          head: main
          pr_title: Merge
          auto_approve: true
