name: Sync Fork
on:
  schedule:
    - cron: "0 5/6 * * *"
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
          ssh-key: "${{ secrets.SSH_KEY }}"
      - name: Set GitHub Actions as commit author
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: containrrr/watchtower
          upstream-branch: main
          branch: main
